import { expect, test } from "vitest"
import { AllSchemas, getSchema } from "../src/models/entities"
import { PropertyAccessLevel } from "../src/models/properties"
import spec from "./data/contributeFormLevels.json"

/**
 * Labels double as the keys of a materialized entity's `data` and as the
 * lookup key for `getSchemaProp`, so two properties sharing one within a
 * schema makes the second unreachable.
 */
test("no schema has two properties with the same label", () => {
  const collisions: string[] = []
  for (const schema of AllSchemas) {
    const seen = new Set<string>()
    for (const prop of schema.properties) {
      if (seen.has(prop.label)) collisions.push(`${schema.name}: "${prop.label}"`)
      seen.add(prop.label)
    }
  }
  expect(collisions).toEqual([])
})

/**
 * `contributeFormLevels.json` carries the field labels and contributor tiers
 * from the Contribute Form Levels workbook, joined to the schema by the
 * dataset mnemonics in the Django models. It is regenerated by
 * `scripts/genContributeFormLevels.ts`, which needs the workbook and a
 * voyages-api checkout; doing so is a deliberate act — an unexplained diff
 * here means the schema drifted from the spec rather than the other way round.
 *
 * Entries are keyed by backing field, which the spec sync did not touch, so a
 * label rename shows up as a mismatch rather than a lost entry. Sections whose
 * fields the app doesn't model (Enslavers, Sources) have no entries.
 */
test("field labels and contributor tiers match the Contribute Form Levels spec", () => {
  const labelMismatches: string[] = []
  const levelMismatches: string[] = []
  const missing: string[] = []

  for (const entry of spec.entries) {
    const schema = getSchema(entry.schema)
    const prop = schema.properties.find(
      (p) => p.backingField === entry.backingField || p.backingField === `${entry.backingField}_id`
    )
    if (prop === undefined) {
      missing.push(`${entry.schema}.${entry.backingField}`)
      continue
    }
    if (prop.label !== entry.label)
      labelMismatches.push(`${entry.schema}.${entry.backingField}: spec "${entry.label}", schema "${prop.label}"`)
    if (prop.accessLevel !== entry.level)
      levelMismatches.push(
        `${entry.schema}.${entry.backingField}: spec ${PropertyAccessLevel[entry.level]}, schema ${
          prop.accessLevel === undefined ? "(none)" : PropertyAccessLevel[prop.accessLevel]
        }`
      )
  }

  expect(missing).toEqual([])
  expect(labelMismatches).toEqual([])
  expect(levelMismatches).toEqual([])
})

/**
 * The spec orders the fields within each section, and the form renders them in
 * declaration order, so the two have to agree.
 */
test("fields appear in the order the spec lists them", () => {
  const inversions: string[] = []
  const bySchema = new Map<string, typeof spec.entries>()
  for (const entry of spec.entries) {
    if (!bySchema.has(entry.schema)) bySchema.set(entry.schema, [])
    bySchema.get(entry.schema)!.push(entry)
  }
  for (const [schemaName, entries] of bySchema) {
    const order = getSchema(schemaName).properties.map((p) => p.backingField)
    const positions = entries.map((e) => ({
      label: e.label,
      at: order.findIndex((f) => f === e.backingField || f === `${e.backingField}_id`)
    }))
    for (let i = 0; i < positions.length - 1; i++)
      if (positions[i].at > positions[i + 1].at)
        inversions.push(`${schemaName}: "${positions[i].label}" should precede "${positions[i + 1].label}"`)
  }
  expect(inversions).toEqual([])
})
