import { expect, test } from "vitest"
import { AllSchemas, getSchema } from "../src/models/entities"
import { PropertyAccessLevel } from "../src/models/properties"
import spec from "./data/contributeFormLevels.json"

/**
 * Labels double as the keys of a materialized entity's `data` and as the
 * lookup key for `getSchemaProp`, so two properties sharing one within a
 * schema makes the second unreachable.
 */
test("no schema has two properties with the same label", () => {
  const collisions: string[] = []
  for (const schema of AllSchemas) {
    const seen = new Set<string>()
    for (const prop of schema.properties) {
      if (seen.has(prop.label)) collisions.push(`${schema.name}: "${prop.label}"`)
      seen.add(prop.label)
    }
  }
  expect(collisions).toEqual([])
})

/**
 * `contributeFormLevels.json` carries the field labels and contributor tiers
 * from the Contribute Form Levels workbook, joined to the schema by the
 * dataset mnemonics in the Django models. It is regenerated by
 * `scripts/genContributeFormLevels.ts`, which needs the workbook and a
 * voyages-api checkout; doing so is a deliberate act — an unexplained diff
 * here means the schema drifted from the spec rather than the other way round.
 *
 * Entries are keyed by backing field, which the spec sync did not touch, so a
 * label rename shows up as a mismatch rather than a lost entry. Sections whose
 * fields the app doesn't model (Enslavers, Sources) have no entries.
 */
test("field labels and contributor tiers match the Contribute Form Levels spec", () => {
  const labelMismatches: string[] = []
  const levelMismatches: string[] = []
  const missing: string[] = []

  for (const entry of spec.entries) {
    const schema = getSchema(entry.schema)
    const prop = schema.properties.find(
      (p) => p.backingField === entry.backingField || p.backingField === `${entry.backingField}_id`
    )
    if (prop === undefined) {
      missing.push(`${entry.schema}.${entry.backingField}`)
      continue
    }
    if (prop.label !== entry.label)
      labelMismatches.push(`${entry.schema}.${entry.backingField}: spec "${entry.label}", schema "${prop.label}"`)
    if (prop.accessLevel !== entry.level)
      levelMismatches.push(
        `${entry.schema}.${entry.backingField}: spec ${PropertyAccessLevel[entry.level]}, schema ${
          prop.accessLevel === undefined ? "(none)" : PropertyAccessLevel[prop.accessLevel]
        }`
      )
  }

  expect(missing).toEqual([])
  expect(labelMismatches).toEqual([])
  expect(levelMismatches).toEqual([])
})

/**
 * The spec orders the fields within each section, and the form renders them in
 * declaration order, so the two have to agree.
 */
test("fields appear in the order the spec lists them", () => {
  const inversions: string[] = []
  const bySchema = new Map<string, typeof spec.entries>()
  for (const entry of spec.entries) {
    if (!bySchema.has(entry.schema)) bySchema.set(entry.schema, [])
    bySchema.get(entry.schema)!.push(entry)
  }
  for (const [schemaName, entries] of bySchema) {
    const order = getSchema(schemaName).properties.map((p) => p.backingField)
    const positions = entries.map((e) => ({
      label: e.label,
      at: order.findIndex((f) => f === e.backingField || f === `${e.backingField}_id`)
    }))
    for (let i = 0; i < positions.length - 1; i++)
      if (positions[i].at > positions[i + 1].at)
        inversions.push(`${schemaName}: "${positions[i].label}" should precede "${positions[i + 1].label}"`)
  }
  expect(inversions).toEqual([])
})

/**
 * A connection row exists to state one link. The column holding that link is
 * NOT NULL in every case here -- a ManyToManyField's auto-created table, or a
 * ForeignKey declared without `null=True` -- so a row without it is refused at
 * publication. The schema has to refuse it first, or an import writes records
 * that can never be published and a form accepts entries that can never be
 * saved.
 */
test("connection links that cannot be null say so", () => {
  const required = [
    ["VoyageCargoConnectionSchema", "cargo_id"],
    ["VoyageAfricanInfoConnectionSchema", "africaninfo_id"],
    ["Voyage Source Connection", "source_id"],
    ["EnslaverRelationRoleConn", "enslaverrole_id"]
  ]
  const nullable = required.filter(([schemaName, backingField]) => {
    const prop = getSchema(schemaName).properties.find(
      (p) => p.backingField === backingField
    )
    return !(prop as { notNull?: boolean } | undefined)?.notNull
  })
  expect(nullable).toEqual([])
})

/**
 * A linked property writes a foreign key column, and Django names those
 * `<relation>_id` -- none of the models these schemas back override
 * `db_column`. Naming the relation instead reads fine, because the fetch
 * endpoint translates a name it does not recognise, and fails on write, where
 * a primary key cannot be assigned to a relation.
 */
test("every linked property names a column, not the relation", () => {
  const relations: string[] = []
  for (const schema of AllSchemas) {
    for (const p of schema.properties) {
      if (p.kind === "linkedEntity" && !p.backingField.endsWith("_id")) {
        relations.push(`${schema.name}.${p.backingField}`)
      }
    }
  }
  expect(relations).toEqual([])
})

/**
 * A stored changeset names the property it changes by uid, so a uid is a value
 * already written down elsewhere rather than a label free to follow its field.
 * These two were derived from a backing field that has since been corrected,
 * and they keep the derivation in force when those changes were written.
 */
test("uids that stored changesets depend on do not move", () => {
  const uidOf = (schemaName: string, label: string) =>
    getSchema(schemaName).properties.find((p) => p.label === label)?.uid
  expect({
    grouping: uidOf("Voyage", "Voyage grouping"),
    date: uidOf("Voyage Source", "Date")
  }).toEqual({
    grouping: "Voyage_voyage_groupings",
    date: "Voyage Source_date"
  })
})

/**
 * Two properties may share a backing field -- a foreign key is often worth both
 * a picker and the raw id behind it -- but only one can be on the form, or the
 * contributor gets two ways to write one column and nothing saying which wins.
 * `Hidden` is what takes the second off every form, editors' included, so that
 * is what counts here as resolved.
 */
test("no backing field is writable from two places on the form", () => {
  const visible = (p: { accessLevel?: PropertyAccessLevel }) =>
    (p.accessLevel ?? PropertyAccessLevel.BeginnerContributor) <
    PropertyAccessLevel.Hidden
  const collisions: string[] = []
  for (const schema of AllSchemas) {
    const byField = new Map<string, string[]>()
    for (const prop of schema.properties) {
      const field = (prop as { backingField?: string }).backingField
      if (!field || !visible(prop)) continue
      byField.set(field, [...(byField.get(field) ?? []), prop.label])
    }
    for (const [field, labels] of byField) {
      if (labels.length > 1) {
        collisions.push(`${schema.name}.${field}: ${labels.join(", ")}`)
      }
    }
  }
  expect(collisions).toEqual([])
})
